development:
  adapter: postgresql
  encoding: unicode
  database: show_list_api_development
  pool: 5
  username: root
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: show_list_api_test
  pool: 5
  username: root
  password:
